import React, { useState, useEffect } from 'react';
import {
  Grid,
  Card,
  CardContent,
  Typography,
  Box,
  IconButton,
  LinearProgress,
  Chip,
  Avatar,
  List,
  ListItem,
  ListItemAvatar,
  ListItemText,
  ListItemSecondaryAction,
  Tooltip,
  Button,
  useTheme
} from '@mui/material';
import {
  People,
  Business,
  DevicesOther,
  AttachMoney,
  TrendingUp,
  TrendingDown,
  AccessTime,
  DirectionsCar,
  Warning,
  CheckCircle,
  Refresh,
  MoreVert,
  ArrowUpward,
  ArrowDownward